### PR TITLE
Use `--repo` when setting known hosts secret

### LINKED ISSUE #293: Bug: known hosts set on wrong repo
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
When using `--repo` on `trellis key generate`, the deploy key and private key secrets are set to the specified repo but the known hosts secret is not.

#### What have you tried?
N/A

#### What insights have you gained?
I'm forgetful

#### Possible solutions
N/A

#### Temporary workarounds
N/A

### Steps To Reproduce

1. Run `trellis key generate --repo MyOrg/MyRepo`

### Expected Behavior

To set known hosts secret to specified repo

### Actual Behavior

Adds ssh known hosts secret to default/wrong repo

### Relevant Log Output

_No response_

### Versions

untagged

### PR DESCRIPTION
**Pull request by codepuncher**
Closes #293

### CODE REVIEW

File: cmd/key_generate.go [hunk 1]
```diff
@@ -193,18 +193,8 @@ func (c *KeyGenerateCommand) Run(args []string) int {
 		}
 	}
 
-	knownHosts := keyscanHosts(strings.Split(c.knownHosts, ","))
-
-	if len(knownHosts) == 0 {
+	if err := setSshKnownHostsSecret(sshKnownHostsSecret, c.knownHosts, c.repo); err != nil {
 		c.UI.Error("Error: could not set SSH known hosts.")
```
Comment (swalkinshaw) [inline cmd/key_generate.go:197]: Needs to be added back after this line

```go
c.UI.Error(err.Error())
```

Comment (codepuncher) [reply cmd/key_generate.go:197]: Thanks; take a look now @swalkinshaw

Comment (swalkinshaw) [reply cmd/key_generate.go:197]: Formatting is off 😅  You can run `gofmt -s -w .`

Comment (codepuncher) [reply cmd/key_generate.go:197]: Ah, sorry about that; the past few PRs have been my first time writing in Go so thanks for letting me know if the command 👍

**Comment by swalkinshaw** [comment]
🎉  thanks
